# Building the container image
steps:
- id: 'Building the image'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '.', '-t', 'gcr.io/$PROJECT_ID/REPO_NAME:$COMMIT_SHA', '-f', 'Dockerfile' ]



# Push the container image
- id: 'Pushing the image to the container'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/REPO_NAME:$COMMIT_SHA']

# Deploy container image to Cloud Run
- id: 'Creating Cloud Deploy'
  name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      gcloud run deploy SERVICE_NAME --service-account=SERVICE_ACCOUNT_NAME --image=gcr.io/$PROJECT_ID/REPO_NAME:$COMMIT_SHA --platform=managed --port=80 --ingress=all  --max-instances=100 --min-instances=1 --memory=2Gi --cpu=4  --region=REGION --project=$PROJECT_ID
options:
  logging: CLOUD_LOGGING_ONLY
